apiVersion: v1
kind: Pod
metadata:
  name: acme-portal
  labels:
    app: acme-portal
    cost-center: marketing
spec:
  containers:
  - name: web
    image: acme/java
    ports:
    - containerPort: 8888
  - name: proxy
    image: proxy
    ports:
    - port: 6443
